# Generated by Django 3.2.4 on 2023-09-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_mysoftware'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mysoftware',
        ),
    ]
