# Generated by Django 3.2.4 on 2023-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('notes_pic', models.ImageField(null=True, upload_to='static/enotespic')),
                ('pdf_notes', models.FileField(null=True, upload_to='static/enotespdf')),
                ('added_date', models.DateField(null=True)),
            ],
        ),
    ]
