# Generated by Django 3.2.4 on 2023-09-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_signup_batchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskdownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('pdf_task', models.FileField(null=True, upload_to='static/dtaskpdf')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.studentbatch')),
            ],
        ),
    ]
