# Generated by Django 3.2.4 on 2023-09-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_taskupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(null=True, upload_to='static/feedbackpic')),
                ('college', models.CharField(max_length=300, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
