# Generated by Django 3.2.4 on 2023-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_submittedtask_answer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='profile',
        ),
        migrations.AddField(
            model_name='feedback',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
