# Generated by Django 3.2.4 on 2023-09-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230923_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='uname',
        ),
    ]
