# Generated by Django 3.2.4 on 2023-09-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=300, null=True)),
                ('college', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
