# Generated by Django 3.2.4 on 2023-09-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='ufeedback',
        ),
    ]
