# Generated by Django 3.2.4 on 2023-09-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_feedback_ufeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdownload',
            name='batch',
        ),
        migrations.DeleteModel(
            name='taskupload',
        ),
        migrations.DeleteModel(
            name='taskdownload',
        ),
    ]
