# Generated by Django 3.2.4 on 2023-09-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20230926_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufeedback',
            name='profile',
            field=models.ImageField(null=True, upload_to='static/feedbackpic'),
        ),
    ]
